#server:
  #port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: ${SSL_PASSWORD}   # 换成你自己的
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  library:
    overdue-days: 30   # 逾期天数，30 表示借出超过 30 天且未还视为逾期，你想改成 7 天就填 7

